---
apiVersion: v1
data:
  metricsRefreshInterval: 24h
  namespaces: '{"exclude":[],"include":[]}'
kind: ConfigMap
metadata:
  labels:
    app: kyverno
    app.kubernetes.io/component: kyverno
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: latest
  name: kyverno-metrics
  namespace: kyverno

