# permissions for end users to view policycontrols.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: policycontrol-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: policy-control-operator
    app.kubernetes.io/part-of: policy-control-operator
    app.kubernetes.io/managed-by: kustomize
  name: policycontrol-viewer-role
rules:
- apiGroups:
  - ibm.github.com
  resources:
  - policycontrols
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ibm.github.com
  resources:
  - policycontrols/status
  verbs:
  - get
