//go:build !ignore_autogenerated
// +build !ignore_autogenerated

//
// Copyright 2022 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KcpKubeConfigSecret) DeepCopyInto(out *KcpKubeConfigSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KcpKubeConfigSecret.
func (in *KcpKubeConfigSecret) DeepCopy() *KcpKubeConfigSecret {
	if in == nil {
		return nil
	}
	out := new(KcpKubeConfigSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KyvernoCR) DeepCopyInto(out *KyvernoCR) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KyvernoCR.
func (in *KyvernoCR) DeepCopy() *KyvernoCR {
	if in == nil {
		return nil
	}
	out := new(KyvernoCR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KyvernoInCluster) DeepCopyInto(out *KyvernoInCluster) {
	*out = *in
	out.OperatorGroup = in.OperatorGroup
	out.Subscription = in.Subscription
	out.KyvernoCR = in.KyvernoCR
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KyvernoInCluster.
func (in *KyvernoInCluster) DeepCopy() *KyvernoInCluster {
	if in == nil {
		return nil
	}
	out := new(KyvernoInCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KyvernoInWorkspace) DeepCopyInto(out *KyvernoInWorkspace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KyvernoInWorkspace.
func (in *KyvernoInWorkspace) DeepCopy() *KyvernoInWorkspace {
	if in == nil {
		return nil
	}
	out := new(KyvernoInWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorGroup) DeepCopyInto(out *OperatorGroup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorGroup.
func (in *OperatorGroup) DeepCopy() *OperatorGroup {
	if in == nil {
		return nil
	}
	out := new(OperatorGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyControl) DeepCopyInto(out *PolicyControl) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyControl.
func (in *PolicyControl) DeepCopy() *PolicyControl {
	if in == nil {
		return nil
	}
	out := new(PolicyControl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyControl) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyControlCluster) DeepCopyInto(out *PolicyControlCluster) {
	*out = *in
	out.IngressTLSSecret = in.IngressTLSSecret
	out.KcpKubeConfigSecret = in.KcpKubeConfigSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyControlCluster.
func (in *PolicyControlCluster) DeepCopy() *PolicyControlCluster {
	if in == nil {
		return nil
	}
	out := new(PolicyControlCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyControlList) DeepCopyInto(out *PolicyControlList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyControl, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyControlList.
func (in *PolicyControlList) DeepCopy() *PolicyControlList {
	if in == nil {
		return nil
	}
	out := new(PolicyControlList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyControlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyControlSpec) DeepCopyInto(out *PolicyControlSpec) {
	*out = *in
	out.PolicyControlCluster = in.PolicyControlCluster
	out.KyvernoInWorkspace = in.KyvernoInWorkspace
	out.KyvernoInCluster = in.KyvernoInCluster
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyControlSpec.
func (in *PolicyControlSpec) DeepCopy() *PolicyControlSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyControlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyControlStatus) DeepCopyInto(out *PolicyControlStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyControlStatus.
func (in *PolicyControlStatus) DeepCopy() *PolicyControlStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyControlStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subscription) DeepCopyInto(out *Subscription) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subscription.
func (in *Subscription) DeepCopy() *Subscription {
	if in == nil {
		return nil
	}
	out := new(Subscription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSecret) DeepCopyInto(out *TLSSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSecret.
func (in *TLSSecret) DeepCopy() *TLSSecret {
	if in == nil {
		return nil
	}
	out := new(TLSSecret)
	in.DeepCopyInto(out)
	return out
}
